### PR TITLE
Freeborn, Freeborn Adventurers, Synchronizer Drone (and more!)

### PR DESCRIPTION
**Pull request by rythos42**
Freeborn:
- LOTS: Cleaned up various places where things looked optional but weren't, some validation fixes.
- Moved Superior Shard to Army Options
- Updated Command Squad to be more usable
    - "Freeborn Command Squad" and "Freeborn Command Squad (Special)" differentiated to ensure army can only take one set of special options
- Feral Squad no longer has validation error for to many ranged weapons
- Added Synchronizer Drones to Vardanari, Command and Light GP Drone

Freeborn Adventurers
- LOTS: Small tweaks in places -- such as removing options that aren't optional, some renaming and validation fixes
- Moved Superior Shard upgrade to Army Options
- Removed "Army Options" entry in favour of individual options selection
- Updated Command squad to be more usable
    - added Synchronizer drone
- Vardanari
    - corrected base points
    - added plasma grenades
    - added X-Sling
    - aded Synchronizer drone
- Domari: Mag guns no longer optional
- Skyraider Command Squad: corrected base points, tweaking options
- Freeborn Heavy Support Team: added plasma bombard and fractal bombard options
- Light General Purpose Drone: added synchronizer drone

Isorian:
    - NuHu Senatexis no longer forced to take a spotter drone
    - Senatex Command Squad given Synchronizer Drone
    - Isorian Nhamak SC Light Support Drone given Synchronizer Drone
        - And renamed from "NC" to "SC"
    - Isorian Andhak SC2 Light Support Drone given Synchronizer Drone

Concord:
    - Added Synchronizer Drone to C3 Strike Command Squad, C3 Drop Command Squad, C3 Strike Squads, C3 Drop Squads, C3D1 Light Support Drone, C3D2 Medium Support Drone, C3D1/GP Light General Purpose Drone
    - Separated Drop Trooper (Lance) to make it clearer that there is only a single Lance in the squad to start.
    - Drop Squad Trooper count was off by 1
    
All:
    Updated Army Options limit for AUX numbers

### CODE REVIEW

**Comment by glasvandrare** [comment]
Published.

**Comment by rythos42** [comment]
Sweet, thanks!

**Comment by glasvandrare** [comment]
So, I've not been able to get the 2.0 tool framework up and running yet,
but I've got a few issues I think we should fix:
*Isorian bikes should be Tactical
*Vardanari; are they correctly costed, as per the errata?
*Missing Xilos version of Kamrana Josen
*Boromite Scout probes too expensive

I'll work on it once I get my java version sorted (but I'm locked to 1.7.0
for the time being...)


//T

**Comment by shammond42** [comment]
I can fix the Boromite scout probe cost. There are a couple other cost issues I want to check while I am in there.

**Pull request merged**
