### PR TITLE
Force Organization Updates

### PR DESCRIPTION
**Pull request by Tvayumat**
Added force selections for all factions and all points values with
correct unit limitations and categories for Army Options.

### CODE REVIEW

**Comment by Tvayumat** [comment]
Removed the generic Force selections and made specific force orgs for each faction, including Ghar Rebels, Freeborn Adventurers, and Boromite Clans.

Also added categories for Army Options limited to 10% of total pts value.

**Comment by clandaith** [comment]
Please make sure you read the rules for uploading and working with battle
scribe files.  The zipped files shouldn't be committed into the
repository.  I'm only reading this on my phone so it appears it is
happening.

**Comment by Tvayumat** [comment]
Nothing I committed was zipped AFAIK. Just a .gstz file.

I'll have a look though, I'm not wholly familiar with all the ins-and-outs yet.

**Comment by Tvayumat** [comment]
I'll have a look though, I'm not wholly familiar with all the ins-and-outs yet.

**Comment by clandaith** [comment]
The .catz files are the compressed ones.  The .cat files aren't.

Have a look at this:

https://github.com/BSData/bsdata/wiki/Developer-Guide

**Comment by Tvayumat** [comment]
That explains the z I guess. Lots to learn. I'll take a look. Hope I didn't gum anything up.

**Comment by clandaith** [comment]
Doubt you did.  I didn't know the difference between them until I did the
same thing.

**Pull request merged**
