### PR TITLE
Removed unneeded < and > from names

### PR DESCRIPTION
**Pull request by clandaith**
For some reason, a lot of "<" and ">" were added to names.  Using VIM, I ran the following search and replace strings:

%s/&lt;\ //g
%s/\ &gt;//g

This removed all the unneeded characters and spaces.

### CODE REVIEW

**Comment by Vescarea** [comment]
It's for keeping the leaders of squads in roster at the top and helps with organising. Removing them makes it all look disorganised.

**Comment by clandaith** [comment]
If that is the case, it should be done to all leaders.  As far as I could tell, it was done "hit or miss".  Plus, it was done to other things besides leaders.  Troopers, units, options, and weapons also had it.  Again, not everything had the <>.

Also, I've never seen anything like that before in any other BS data files.  

I say they should still be removed.

**Comment by Vescarea** [comment]
I wouldn't say it was "hot or miss" they have purposes
Leaders only have it to prioritise them to show closer to the top and <> is mearly to show a tab selection or options. Its both functional and presentation considering everything is numerically and alphabetically sorted. But if you feel it's not required then thats fair enough.

**Comment by glasvandrare** [comment]
I agree with the purpose, but I'm wondering if it couldn't be solved in another way. 
Could we keep this branch open for experimenting with different ways of doing it?

**Comment by clandaith** [comment]
So do we want to go ahead and merge this in or not?

**Comment by Vescarea** [comment]
what do the others think?

Get Outlook for Android

On Wed, Jun 15, 2016 at 2:22 AM +0100, "Troy Davidson" notifications@github.com wrote:

So do we want to go ahead and merge this in or not?

---

**Comment by clandaith** [comment]
I say we go ahead and merge it in.

**Comment by clandaith** [comment]
Closing old pull request.  We don't need to keep it open.

**Pull request closed without merging**
